apiVersion: v2
name: kube-prometheus-stack
description: Prometheus and Grafana monitoring stack for EKS
type: application
version: 1.0.0
appVersion: "80.9.1"

dependencies:
  - name: kube-prometheus-stack
    version: "80.9.1"
    repository: https://prometheus-community.github.io/helm-charts
