apiVersion: v1
kind: Secret
metadata:
  name: user-management-db-secret
  namespace: dev
type: Opaque
stringData:
  DB_HOST: "RDS_ENDPOINT_PLACEHOLDER"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "RDS_PASSWORD_PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: exercises-db-secret
  namespace: dev
type: Opaque
stringData:
  DB_HOST: "RDS_ENDPOINT_PLACEHOLDER"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "RDS_PASSWORD_PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: scores-db-secret
  namespace: dev
type: Opaque
stringData:
  DB_HOST: "RDS_ENDPOINT_PLACEHOLDER"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "RDS_PASSWORD_PLACEHOLDER"
